
CREATE TABLE T_HCP_ESPECIALIDAD (
	Codigo		INTEGER	NOT NULL,
	Nombre		VARCHAR(64)	NOT NULL
);

ALTER TABLE T_HCP_ESPECIALIDAD
	ADD CONSTRAINT spcldd_clave_primaria PRIMARY KEY (Codigo);

CREATE TABLE T_HCP_MEDICAMENTO(
	Codigo		VARCHAR(10)	NOT NULL,
	Nombre		VARCHAR(128)	NOT NULL
);


CREATE TABLE T_HCP_PROFESIONAL_SALUD (
	Identificacion		INTEGER	NOT NULL,
	Nombre			VARCHAR(64)	NOT NULL,
	Tarjeta_profesional 	VARCHAR(20),
	Especialidad		INTEGER	NOT NULL,
	TIPO_CONSULTA  		VARCHAR(1)
);

ALTER TABLE T_HCP_PROFESIONAL_SALUD
	ADD CONSTRAINT prfsld_clave_primaria PRIMARY KEY (Identificacion);

ALTER TABLE T_HCP_PROFESIONAL_SALUD
 	ADD CONSTRAINT prfsld_especialidad
 	FOREIGN KEY (Especialidad)
 REFERENCES T_HCP_ESPECIALIDAD(Codigo);

CREATE TABLE T_HCP_PACIENTE(
	Id				INTEGER NOT NULL,
	Estudiante			INTEGER,
	Funcionario			INTEGER,
	Tipo				VARCHAR(1) NOT NULL,
	Clave_internet			VARCHAR(8)
);

ALTER TABLE T_HCP_PACIENTE
	ADD CONSTRAINT pcnt_clave_primaria
PRIMARY KEY (Id);

CREATE TABLE T_HCP_CALENDARIO_TURNO (
	Fecha 			DATETIME NOT NULL,
	Profesional_salud 	INTEGER NOT NULL,
	Paciente 		INTEGER,
	Estado_turno 		VARCHAR(1) DEFAULT  'N'
);

ALTER TABLE T_HCP_CALENDARIO_TURNO
	ADD CONSTRAINT cldtrn_clave_primaria
	PRIMARY KEY (Fecha, Profesional_salud);

ALTER TABLE T_HCP_CALENDARIO_TURNO
	ADD CONSTRAINT cldtrn_profesional_salud
 	FOREIGN KEY (Profesional_Salud)
	REFERENCES T_HCP_PROFESIONAL_SALUD (Identificacion);

ALTER TABLE T_HCP_CALENDARIO_TURNO
	ADD CONSTRAINT cldtrn_paciente
 	FOREIGN KEY (Paciente)
	REFERENCES T_HCP_PACIENTE (Id);
